tscript/50-bootstrap-user: Add test for incorrect # of args
Usage should continue to print when passing invalid argument(s), even after
valid arguments get added.

diff --git a/tscript/50-bootstrap-user b/tscript/50-bootstrap-user
--- a/tscript/50-bootstrap-user
+++ b/tscript/50-bootstrap-user
@@ -13,6 +13,15 @@ export HOME="$PROJDIR/.build/tscript/$(basename "$0")/home"
 rm -rf "$HOME"; mkdir -p "$HOME"
 export LOGNAME=dh_test
 export DH_BOOTSTRAP_USERS="file://$PROJDIR/dh/bootstrap-users"
+
+expected='Usage:'
+  output=$($PROJDIR/bootstrap-user --a-bogus-argument || true)
+  actual="${output:0:6}"
+[[ $expected == $actual ]] || die 30 "Failure:
+  Expected: $expected
+    Actual: $actual
+"
+
 $PROJDIR/bootstrap-user
 
 expected=',inb4  _inb4  cpd  dot-home'
